### ISSUE TITLE
Feedback reprocuibility

### ISSUE THREAD

**Issue by DLiangUU** [Peter-UU-2021/workshop#1]
**1. What project did you reproduce (include the link)?**

-> Reproduced the project https://github.com/Peter-UU-2021/workshop/tree/master/good-enough-project-template 

**2. Does the project have the following on it's GitHub repository?**

- [x] README
- [x] A license
- [x] Citation information
- [x] Requirements for running the code (dependencies)
- [x] An understandable folder structure

**3. What did you appreciate about the project's repository?**

-> The repository is simple and understandable. The dependencies and installation are provided.

**4. Do you have any suggestions for improvement to the repository?**

-> If the project grows, it can be nice to have more folders. e.g. a folders for the data if there are multiple sets of data to be used. 

**5. Did you manage to run the project successfully?**

- [ ] Yes
- [ ] Largely
- [ ] No
- [x] Other (please specify): I had troubles cloning the repository

**6. Where did you have to give up reproducing this repository (if applicable)?**

->

**7. Did you have to go into the code?**

- [ ] Yes
- [ ] No
- [x] I didn't have to, but I had time left/was intrigued, so I did it anyway!

**8. If you looked at the code: what did you like?**

-> It is a nice setup and very simple to read. It could be nice to describe some of the variables that are used. 

**9. If you looked at the code, what would be a single line of advice you want to pass on to it's author?**

-> Personally, I would have some more comments. 

**10. Any final comments to the author?**

-> Overall a fine repository! 

**11. Do you think the class will benefit from a live demo of the reproduction of this project? Why/what can we learn?**

->

**Comment by Peter-UU-2021** [comment]
Thanks for the comments
